export const POPULAR_FONTS = [
    "Inter",
    "Roboto",
    "Open Sans",
    "Montserrat",
    "Lato",
    "Poppins",
    "Roboto Condensed",
    "Source Sans 3",
    "Oswald",
    "Roboto Mono",
    "Raleway",
    "Ubuntu",
    "PT Sans",
    "Playfair Display",
    "Nunito",
    "Merriweather",
    "Noto Sans",
    "Rubik",
    "Kanit",
    "Lora",
    "Arvo",
    "Titillium Web",
    "Heebo",
    "Work Sans",
    "Fira Sans",
    "Quicksand",
    "Josefin Sans",
    "Barlow",
    "Anton",
    "DM Sans",
    "Gabarito",
    "Fraunces",
    "Libre Baskerville",
    "Archivo",
    "Exo 2",
    "Mukta",
    "Bebas Neue",
    "Pacifico",
    "Caveat",
    "Dancing Script",
    "Permanent Marker",
    "Comfortaa",
    "Orbitron",
    "Righteous",
    "Cinzel",
    "Abril Fatface",
    "Shadows Into Light",
    "Indie Flower",
    "Lobster",
    "Amatic SC",
    "Sacramento",
    "Satisfy",
    "Courgette",
    "Kaushan Script",
    "Yellowtail",
    "Cookie",
    "Great Vibes",
    "Teko",
    "Rajdhani",
    "Hind",
    "Karla",
    "Inconsolata",
    "Bitter",
    "Crimson Text",
    "Libre Franklin",
    "Space Grotesk",
    "Syncopate",
    "Unbounded",
    "Outfit",
    "Schibsted Grotesk",
    "Instrument Sans",
    "Plus Jakarta Sans",
    "Manrope",
    "Questrial",
    "Fredoka",
    "Urbanist",
    "Lexend",
    "Catamaran",
    "Varela Round",
    "Nanum Gothic",
    "Maven Pro",
    "Asap",
    "Josefin Slab",
    "Old Standard TT",
    "Play",
    "Signika",
    "Signika Negative",
    "Russo One",
    "Patua One",
    "Domine",
    "Spectral",
    "Crimson Pro",
    "Volkhov",
    "Cardo",
    "Faustina",
    "Cormorant Garamond",
    "Zilla Slab",
    "Chivo",
    "Public Sans"
];

export const getGoogleFontUrls = (fontFamily: string) => {
    const family = fontFamily.replace(/\s+/g, '+');
    return `https://fonts.googleapis.com/css2?family=${family}:wght@400;500;600;700&display=swap`;
};
